# stage1 as builder
FROM node:18.12.1-alpine3.16 as builder

# copy the package.json to install dependencies
COPY ./frontend/package.json ./frontend/package-lock.json ./

# Install the dependencies and make the folder
RUN npm install
RUN mkdir /react-ui && \
    mv ./node_modules ./react-ui

WORKDIR /react-ui

COPY ./frontend .

# Build the project and copy the files
RUN npm run build


FROM nginx:1.23.2-alpine

#!/bin/sh

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

## Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*

# Copy from the stahg 1
COPY --from=builder /react-ui/build /usr/share/nginx/html

EXPOSE 3000 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]